#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: database-hood-user 
  CLOUD_SQL_PASSWORD: password$
  CLOUD_SQL_DATABASE_NAME: database-hood-db
  CLOUD_SQL_CONNECTION_NAME: database-hood-2:us-east1:database-hood
